source 'http://rubygems.org'

gem 'rails', '3.0.5'

group :production do
  gem "mysql2"
  gem "rack", "1.2.2"
end
group :development, :test do
  gem "sqlite3"
  gem 'web-app-theme', '>= 0.6.2'
end
gem 'capistrano'

gem 'jquery-rails', '>= 0.2.6'